name: 🐛 Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!
  - type: input
    id: version
    attributes:
      label: Version
      description: App or package version (e.g. v1.2.3)
      placeholder: vX.Y.Z
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options: [macOS, Windows, Linux, Other]
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Clear, step-by-step description
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: "1. …\n2. …\n3. …"
